cookie:
  expiry_days: 30
  key: {COOKIE_KEY} # Must be a string
  name: "some_cookie_name"
credentials:
  usernames:
    jsmith:
      email: "jsmith@gmail.com"
      failed_login_attempts: 0 # Will be managed automatically
      first_name: "John"
      last_name: "Smith"
      logged_in: False # Will be managed automatically
      password: {USER1_PASSWORD} # Will be hashed automatically
      roles: ["admin", "editor", "viewer"]
    datapaq:
      email: "datapaq@gmail.com"
      failed_login_attempts: 0 # Will be managed automatically
      first_name: "datapaq"
      last_name: "essais"
      logged_in: False # Will be managed automatically
      password: {USER2_PASSWORD} # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    rbriggs:
      email: "rbriggs@gmail.com"
      failed_login_attempts: 0 # Will be managed automatically
      first_name: "Rebecca"
      last_name: "Briggs"
      logged_in: False # Will be managed automatically
      password: {USER3_PASSWORD} # Will be hashed automatically
      roles: # Optional
      - viewer

